### ISSUE TITLE
[ARV-39] Storybook 설정

### ISSUE THREAD

**Issue by nxnaxx** [prgrms-web-devcourse-final-project/WEB1_1_Allreva_FE#10]
### 👥 팀 선택 (Team)

FE

### 🏷️ 라벨 선택 (Label)

FEAT

### 🎟️ 상위 작업 (Ticket Number)

ARV-28

### 🌳 브랜치명 (Branch)

feat/set-up-storybook

### 📝 상세 내용(Description)

스토리북 설정

### ✅ 체크리스트(Tasks)

- [ ] Storybook 설정
- [ ] 관련 테스트 확인

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Update package.json to include Storybook dependencies and scripts for running and building Storybook

You can review changes in this commit: https://github.com/lkilu6456546/prgrms-web-devcourse-final-project-WEB1_1_Allreva_FE-10/commit/662d2868dee5b084eedfc08f7dc30d0d0c995261.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
