### ISSUE TITLE
[ARV-41] 폴더 구조 설정

### ISSUE THREAD

**Issue by CH4MD0M** [prgrms-web-devcourse-final-project/WEB1_1_Allreva_FE#12]
### 👥 팀 선택 (Team)

FE

### 🏷️ 라벨 선택 (Label)

FEAT

### 🎟️ 상위 작업 (Ticket Number)

ARV-28

### 🌳 브랜치명 (Branch)

feat/set-up-directory

### 📝 상세 내용(Description)

폴더 구조를 설정합니다

### ✅ 체크리스트(Tasks)

- [ ] 폴더 구조를 설정

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Created new directories and moved existing files to set up the project structure. Added placeholder files for common components and utilities.

You can review changes in this commit: https://github.com/lkilu6456546/prgrms-web-devcourse-final-project-WEB1_1_Allreva_FE-10/commit/6c0f53bc657feca6932d36ced59a5e825107afc6.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
